name: Doco CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 'Build Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        id: cache
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup PNPM cache
        env:
          STORE_PATH: ${{ steps.cache.outputs.STORE_PATH }}
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Insall dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Build
        run: pnpm run docs:build